### ISSUE TITLE
Consider auto-reloading on folder rename

### ISSUE THREAD

**Issue by pun-ky** [wttech/aem-stubs#13]
e.g rename /var/stubs/wiremock/samples to /var/stubs/wiremock/examples 
because "samples" are excluded by default OSGi config of Stub Manager.

scripts after rename should be loaded automatically but they are not.
this is a very edge case... but probably could be somehow better handled.

ensure that the changes made will not impact launching auto-reloading too many times unnecessarily

**Comment by krystian-panek-vmltech** [comment]
no longer valid for v4; the stubs are not cached. always fresh data (currently saved version of stub scripts) is in use
