### ISSUE TITLE
Support easy fake data generation

### ISSUE THREAD

**Issue by pun-ky** [wttech/aem-stubs#14]
Consider integrating library like https://github.com/DiUS/java-faker
and exposing it in stub scripts as variable `faker` for easy generation stubs with fake data looking like the real data.

**Comment by pun-ky** [comment]
what is import for me is to cover both cases:

1. generating stub which is not changed after refreshing my SPA app which is using stubbed data
2. generating stub which is changing after refreshing my SPA app which is using stubbed data

both cases are valid under different circumstances.

in other words

1. stubs response will be determined in time of reloading aem-stubs
2. stubs response is determined in time of requesting particular stub via templating

**Comment by krystian-panek-vmltech** [comment]
implemented in v4
