### ISSUE TITLE
Automatic sending of CORS headers on stub responses

### ISSUE THREAD

**Issue by marcinkp** [wttech/aem-stubs#48]
WireMock supports sending CORS headers for stub responses. 

Add configuration for enable automatic sending of CORS headers on stub responses like in WM.

### Use case
Consider developing SPA - for exaple react app. Application during development is avaiable on port 3000, but View as Published app is available on port 4502. It is not possible to handle it- because of CORS. You can add headers on mocks, but easier way would be to have possibility on tool by default

**Comment by pun-ky** [comment]
please describe real life use case

**Comment by marcinkp** [comment]
Implemented in 2.1.0
