### ISSUE TITLE
Maven artifacts not available on dl.bintray repository (forbidden)

### ISSUE THREAD

**Issue by francisbonheur** [wttech/aem-stubs#54]
It is not possible to donwload AEM-STUB artifacts via the public maven repository because of forbidden error
https://dl.bintray.com/cognifide/maven-public/com/cognifide/aem/stubs/wiremock-all/2.1.0/wiremock-all-2.1.0.zip

It is required to be able to deploy the packages on AEMaaCS instances.

Can you make it available again ?

**Comment by krystian-panek-wttech** [comment]
AEMaaCS as far as I know supports private Maven repositories so you could host it on your own.

**Comment by krystian-panek-wttech** [comment]
Hosting zips on Maven Central is forbidden or at least not straightforward. Bintray is no longer an option.

**Comment by royteeuwen** [comment]
what do you mean it's forbidden @krystian-panek-wttech ? A lot of the frameworks we use are available as zip on maven central? It would be nice to have aem-stubs available in maven central

**Comment by krystian-panek-wttech** [comment]
Maybe it was only a case when I tried to propagate it from jcenter to Maven central. I was consulting it with jfrog support team even 😁

**Comment by krystian-panek-wttech** [comment]
I have no time / resources to do that. Sorry.

**Comment by pun-ky** [comment]
I will push it some day to https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

```
<distributionManagement>
   <repository>
     <id>github</id>
     <name>GitHub Wttech AEM Stubs</name>
     <url>https://maven.pkg.github.com/wttech/aem-stubs</url>
   </repository>
</distributionManagement>
```

**Comment by royteeuwen** [comment]
Super thanks for the update
