### ISSUE TITLE
Upgrade to the latest Groovy version

### ISSUE THREAD

**Issue by royteeuwen** [wttech/aem-stubs#55]
We are checking to upgrade the AEM Groovy console to the latest groovy version. It would be handy if AEM Stubs also uses the latest version as to not have to have two groovy bundles deployed to the same environment

I am willing to make a PR / test this out. Are you willing to merge this or is this project abandoned?

**Comment by krystian-panek-wttech** [comment]
It's nice to know that you are using stubs. I am open to merge and release anything that is valuable. Project is not abandoned but to be honest I am just owning many tools right now and I am not able to implement upgrades upfront but rather on demand. If you will provide PR it will be definitely the best. Cheers

**Comment by royteeuwen** [comment]
Created https://github.com/wttech/aem-stubs/pull/56 
Go ahead and review :) I have tested it with the sample files

**Comment by krystian-panek-wttech** [comment]
looks good, today I will test it and release it

**Comment by krystian-panek-wttech** [comment]
released, thanks ;)

https://github.com/wttech/aem-stubs/releases/tag/3.0.0
